/** Greek UI labels — default app locale (el). */
export const el = {
  navPrimary: "Κύρια",
  signIn: "Σύνδεση",
  email: "Email",
  password: "Κωδικός πρόσβασης",
  settings: "Ρυθμίσεις",
  closeSettings: "Κλείσιμο ρυθμίσεων",
  contacts: "Επαφές",
  partnerCodes: "Κωδικοί συνεργατών",
  appearance: "Εμφάνιση",
  integrations: "Ενσωματώσεις",
  tasks: "Εργασίες",
  everyone: "Όλοι",
  newTask: "Νέα εργασία",
  title: "Τίτλος",
  due: "Προθεσμία",
  create: "Δημιουργία",
  chooseAssignees: "Επιλογή υπεύθυνων",
  deptEngineering: "Αρχιτεκτονική",
  deptSales: "Πωλήσεις",
  iFinished: "Τελείωσα",
  yesSubmit: "Ναι, υποβολή",
  completed: "Ολοκληρωμένες",
  appointments: "Ραντεβού",
  newAppointment: "Νέο ραντεβού",
  starts: "Έναρξη",
  createAppointment: "Δημιουργία ραντεβού",
  cancelAppointment: "Ακύρωση ραντεβού",
  yesCancelAppointment: "Ναι, ακύρωση ραντεβού",
  canceled: "Ακυρωμένα",
  recurring: "Επαναλαμβανόμενο",
  recurringMeeting: "Επαναλαμβανόμενη συνάντηση",
  numberOfMeetings: "Αριθμός συναντήσεων",
  edit: "Επεξεργασία",
  saveChanges: "Αποθήκευση αλλαγών",
  notConnected: "Μη συνδεδεμένο",
  connectGoogleCalendar: "Σύνδεση Google Calendar",
  allChats: "Όλες οι συνομιλίες",
  newDm: "Νέο DM",
  chats: "Συνομιλίες",
  messagePlaceholder: "Μήνυμα…",
  send: "Αποστολή",
  unsend: "Ανάκληση",
  uploading: "Μεταφόρτωση",
} as const;
